/**
  clipboard.js: get/set data via clipboard.
  for google extension, you need to enable permissions in manifest.json file:
  "clipboardRead" and "clipboardWrite"
 **/
var prefix = "[CLIPBOARD]: ";

/*-----------    --------------*/
// Generated by CoffeeScript 1.4.0
(function() {
  var Clipboard, root;

  Clipboard = {
      // publics
    copy: function(data) {
        var textArea;
        textArea = this._createTextArea();
        textArea.value = data;
        document.body.appendChild(textArea);
        textArea.select();
        var result = document.execCommand("Copy");
        document.body.removeChild(textArea);
        return result;
    },
    paste: function() {
        var textArea, value;
        textArea = this._createTextArea();
        document.body.appendChild(textArea);
        textArea.focus();
        document.execCommand("Paste");
        value = textArea.value;
        document.body.removeChild(textArea);
        return value;
    },

    // privates
    _createTextArea: function() {
        var textArea;
        textArea = document.createElement("textarea");
        textArea.style.position = "absolute";
        textArea.style.left = "-100%";
        return textArea;
    }
  };

  root = typeof exports !== "undefined" && exports !== null ? exports : window;

  root.Clipboard = Clipboard;

}).call(this);
/*END*/
